### PR TITLE
fix: only output greeting message on first install

### LINKED ISSUE #39: Output message only once per installation
With the latest Flow, that uses shrinkwrap packages, you see the info message three times during `npm install`

```
> @vaadin/vaadin-usage-statistics@2.0.4 postinstall .../node_modules/@vaadin/vaadin-core-shrinkwrap/node_modules/@vaadin/vaadin-usage-statistics
> node check.js


    Vaadin collects development time usage statistics to improve this product. To opt-out, either run:
    npm explore @vaadin/vaadin-usage-statistics -- npm run disable
    to store disable statistics for the machine, or add
    "vaadin": { "disableUsageStatistics": true }
    to the project package.json and re-run npm install to disable statistics for the project.

    For more details, see https://github.com/vaadin/vaadin-usage-statistics
  

> @vaadin/vaadin-usage-statistics@2.0.4 postinstall .../node_modules/@vaadin/vaadin-shrinkwrap/node_modules/@vaadin/vaadin-usage-statistics
> node check.js


    Vaadin collects development time usage statistics to improve this product. To opt-out, either run:
    npm explore @vaadin/vaadin-usage-statistics -- npm run disable
    to store disable statistics for the machine, or add
    "vaadin": { "disableUsageStatistics": true }
    to the project package.json and re-run npm install to disable statistics for the project.

    For more details, see https://github.com/vaadin/vaadin-usage-statistics
  

> @vaadin/vaadin-usage-statistics@2.0.4 postinstall .../node_modules/@vaadin/vaadin-usage-statistics
> node check.js


    Vaadin collects development time usage statistics to improve this product. To opt-out, either run:
    npm explore @vaadin/vaadin-usage-statistics -- npm run disable
    to store disable statistics for the machine, or add
    "vaadin": { "disableUsageStatistics": true }
    to the project package.json and re-run npm install to disable statistics for the project.

    For more details, see https://github.com/vaadin/vaadin-usage-statistics

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #39

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-usage-statistics/40)

### CODE REVIEW

File: check.js [hunk 1]
```diff
@@ -1,6 +1,9 @@
 var fs = require('fs');
 
 const disabledForMachine = process.env.npm_package_config_disabled;
+const greetingLogged = process.env.npm_package_config_logged;
+const optoutLogged = process.env.npm_package_config_optout;
```
Comment (Artur-) [inline check.js]: This would be less confusing is named `optoutLogged` or similar. Now it is easy to confuse it with `disabled` (which actually means that the user has optedout)

Comment (web-padawan) [reply check.js]: Changed.
